spring:
  sql:
    init:
      mode: "always"
  datasource:
    url: "jdbc:h2:file:./db/filmorate"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: "password"
logging:
  level:
    org:
      zalando:
        logbook: "TRACE"